### PR TITLE
Clarify usage of IPC event pools

### PR DESCRIPTION
**Pull request by jandres742**
Resolves: #102

### CODE REVIEW

**Review by MichalMrozek — COMMENTED** [review]
The requirement is other way around.
We can still import event pool created with root device on sub device. (so there is no requirement that on importer side we need to have at least x sub devices)
But we cannot import event pool created with sub device on root device containing 2 sub devices.

**Comment by jandres742** [comment]
> The requirement is other way around. We can still import event pool created with root device on sub device. (so there is no requirement that on importer side we need to have at least x sub devices) But we cannot import event pool created with sub device on root device containing 2 sub devices.

thanks @MichalMrozek . Please see update.

**Review by MichalMrozek — COMMENTED** [review]
lgtm

**Comment by jandres742** [comment]
thanks @MichalMrozek .

@wdamon-intel : please check.

**Review by wdamon-intel — APPROVED** [review]

**Review by MichalMrozek — APPROVED** [review]

**Pull request merged**
