### PR TITLE
New firmware API for logging

### PR DESCRIPTION
**Pull request by sanilkumar0**
Resolves: oneapi-src/level-zero-spec#277

### CODE REVIEW

**Comment by aravindksg** [comment]
@sanilkumar0 the original issue https://github.com/oneapi-src/level-zero-spec/issues/185 was closed, could you please create new one and add that as reference to this PR? it makes it easy to track for releases

**Review by aravindksg — COMMENTED** [review]
API definition looks good to me

**Comment by aravindksg** [comment]
@joshuaranjan @saik-intel @AshwinKumarKulkarni

**Comment by joshuaranjan** [comment]
lgtm

**Review by AshwinKumarKulkarni — APPROVED** [review]
lgtm

**Pull request merged**
